version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "your_minio_root_user"
      MINIO_ROOT_PASSWORD: "your_minio_root_password"
    volumes:
      - ~/mnt/drive-1:/data
    command: server /data --console-address ":9001"
    restart: always